dist: trusty

language: php

php:
  - 7.1
  - 7.2
  - nightly

before_script:
  - composer install

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  webhooks: https://ci-notification.limenet.xyz/dev/webhook
