language: php

php:
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION="5.5.*"
  - LARAVEL_VERSION="5.6.*"
  - LARAVEL_VERSION="5.7.*"
  - LARAVEL_VERSION="5.8.*"
  - LARAVEL_VERSION="^6.0"

install:
  - rm composer.lock
  - composer require illuminate/support:${LARAVEL_VERSION}

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  webhooks: https://ci-notification.limenet.xyz/dev/webhook
